apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-176
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-176
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-177
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-177
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-178
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-178
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-179
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-179
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-180
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-180
    importPolicy: {}
    referencePolicy:
      type: Local
