apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-265
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-265
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-266
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-266
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-267
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-267
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-268
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-268
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-269
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-269
    importPolicy: {}
    referencePolicy:
      type: Local
