apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-240
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-240
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-241
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-241
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-242
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-242
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-244
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-244
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-245
    from:
      kind: DockerImage
      name: quay.io/css-qe/iot-consumer:0.3.2-245
    importPolicy: {}
    referencePolicy:
      type: Local
