main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: css-qe
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: css-qe
    email: css-qe@redhat.com
    dev_revision: main

  s3:
    bucket:
      name: qe-ie-bucket
      region: us-west-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
